In [1]:
import pandas as pd

In [2]:
# Read the metadata CSV file

metadata_df_1 = pd.read_csv('metadata_source/InTouch-RP-USIT-IBC.csv')
metadata_df_2 = pd.read_csv('metadata_source/VALID-CONTENT-DETAILS-IT.csv')
metadata_df_3 = pd.read_csv('metadata_source/VALID-CONTENT-DETAILS-PRS-v1.0 (1).csv')
metadata_df_4 = pd.read_csv('metadata_source/VALID-CONTENT-DETAILS-WEC-v2.0 (1).csv')
main_metadata_df = pd.read_excel('metadata_source/MVP3_ingested_documents.xlsx')

### Explore the columns and its data types

In [3]:
# Explore the columns and data types of the metadata DataFrames
print("Metadata DataFrame 1:")
print(metadata_df_1.info())

Metadata DataFrame 1:
<class 'pandas.DataFrame'>
RangeIndex: 6030 entries, 0 to 6029
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         6030 non-null   str
 1   contentid                     6030 non-null   int64
 2   contenttype                   6030 non-null   str
 3   contentsubtype                5274 non-null   str
 4   submittedforldap              6030 non-null   str
 5   submittedforfirstname         6028 non-null   str
 6   reviewdate                    856 non-null    str
 7   approved_rejecteddate         1550 non-null   str
 8   approved_rejectedbyfirstname  1536 non-null   str
 9   approved_rejectedbylastname   1536 non-null   str
 10  keywords                      5098 non-null   str
 11  lastmodifieddate1             6030 non-null   str
 12  lastmodifiedbyldap            6030 non-null   str
 13  lastmodifiedbyfirstname       3296 non-null   str
 14  lastmodifiedbylastname        3296 non-null   str
 15  lastmodifiedby                6030 non-null   str
 16  submittedforlastname          6028 non-null   str
 17  submittedforemail             6012 non-null   str
 18  helpdeskname                  6030 non-null   str
 19  submitterldap                 6030 non-null   str
 20  segmentname                   6030 non-null   str
 21  submitteddate                 6030 non-null   str
 22  issuetypecode                 4620 non-null   float64
 23  issuesummary                  6030 non-null   str
 24  parent_helpdeskid             20 non-null     float64
 25  contentsummary                5354 non-null   str
 26  submittedforarea              3642 non-null   str
 27  submittedforgeomarket         3642 non-null   str
 28  submittedforcountry           6028 non-null   str
 29  submittedforlocation          3814 non-null   str
 30  lastmodifieddate              6030 non-null   str
 31  categoryid                    6030 non-null   int64
 32  ind_primary                   4994 non-null   str
 33  category_path                 6030 non-null   str
dtypes: float64(2), int64(2), str(30)
memory usage: 1.6 MB
None

In [4]:
print("\nMetadata DataFrame 2:")    
print(metadata_df_2.info())

Metadata DataFrame 2:
<class 'pandas.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   version                     174 non-null    int64
 1   event                       174 non-null    str
 2   contentid                   174 non-null    int64
 3   segmentid                   174 non-null    int64
 4   helpdeskid                  174 non-null    int64
 5   act_helpdeskid              174 non-null    int64
 6   status                      174 non-null    int64
 7   action_by                   0 non-null      float64
 8   assigned_individual         174 non-null    str
 9   title                       174 non-null    str
 10  object_summary              174 non-null    str
 11  submitted_for_area          50 non-null     str
 12  submitted_for_name          174 non-null    str
 13  submitted_for_country       174 non-null    str
 14  submitted_for_geomarket     50 non-null     str
 15  submitted_for_location      123 non-null    str
 16  submitted_for_ldap          174 non-null    str
 17  submitted_year              174 non-null    int64
 18  submitted_month             174 non-null    str
 19  submitted_day               174 non-null    int64
 20  lastmodified_year           174 non-null    int64
 21  lastmodified_month          174 non-null    str
 22  lastmodified_day            174 non-null    int64
 23  ind_publicuser              174 non-null    int64
 24  num_file_attachments        174 non-null    int64
 25  keywords                    174 non-null    str
 26  business_line               174 non-null    str
 27  content_type                174 non-null    str
 28  content_subtype             148 non-null    str
 29  primary_mnemonic            160 non-null    str
 30  secondary_mnemonic          1 non-null      str
 31  media_type_id               0 non-null      float64
 32  primary_class               174 non-null    str
 33  quest_ids                   18 non-null     str
 34  content_authors             174 non-null    str
 35  ref_page                    162 non-null    str
 36  ref_page_data               162 non-null    str
 37  category_paths              174 non-null    str
 38  ind_whatsnew                174 non-null    int64
 39  ind_outstanding             174 non-null    int64
 40  scope                       138 non-null    str
 41  votesignal                  174 non-null    int64
 42  relatedtechalertcount       14 non-null     float64
 43  status_label                0 non-null      float64
 44  sophia_restricted           174 non-null    int64
 45  content_subtype_id          174 non-null    int64
 46  access_groups               174 non-null    str
 47  deny_groups                 174 non-null    str
 48  page_views                  174 non-null    int64
 49  content_type_boost          174 non-null    int64
 50  typeid                      174 non-null    int64
 51  template_field              0 non-null      float64
 52  relatedto                   60 non-null     float64
 53  lastmodifieddatevalid_day   160 non-null    float64
 54  lastdatevalid_month         160 non-null    str
 55  lastmodifieddatevalid_year  160 non-null    float64
 56  helpdeskname                174 non-null    str
 57  segmentname                 174 non-null    str
 58  parent_helpdesk_id          0 non-null      float64
 59  category_name               60 non-null     str
 60  last_modified_date          174 non-null    str
 61  submitted_date              174 non-null    str
 62  object_content              173 non-null    str
 63  object_refpage_data         1 non-null      str
 64  url                         174 non-null    str
dtypes: float64(9), int64(20), str(36)
memory usage: 88.5 KB
None

In [5]:
print("\nMetadata DataFrame 3:")
print(metadata_df_3.info())

Metadata DataFrame 3:
<class 'pandas.DataFrame'>
RangeIndex: 2438 entries, 0 to 2437
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   version                     2438 non-null   int64
 1   event                       2438 non-null   str
 2   contentid                   2438 non-null   int64
 3   segmentid                   2438 non-null   int64
 4   helpdeskid                  2438 non-null   int64
 5   act_helpdeskid              2438 non-null   int64
 6   status                      2438 non-null   int64
 7   action_by                   0 non-null      float64
 8   assigned_individual         2436 non-null   str
 9   title                       2438 non-null   str
 10  object_summary              2438 non-null   str
 11  submitted_for_area          2335 non-null   str
 12  submitted_for_name          2438 non-null   str
 13  submitted_for_country       2438 non-null   str
 14  submitted_for_geomarket     2335 non-null   str
 15  submitted_for_location      2275 non-null   str
 16  submitted_for_ldap          2438 non-null   str
 17  submitted_year              2438 non-null   int64
 18  submitted_month             2438 non-null   str
 19  submitted_day               2438 non-null   int64
 20  lastmodified_year           2438 non-null   int64
 21  lastmodified_month          2438 non-null   str
 22  lastmodified_day            2438 non-null   int64
 23  ind_publicuser              2438 non-null   int64
 24  num_file_attachments        2438 non-null   int64
 25  keywords                    2438 non-null   str
 26  business_line               2438 non-null   str
 27  content_type                2438 non-null   str
 28  content_subtype             2066 non-null   str
 29  primary_mnemonic            2435 non-null   str
 30  secondary_mnemonic          8 non-null      str
 31  media_type_id               3 non-null      str
 32  primary_class               2423 non-null   str
 33  quest_ids                   155 non-null    str
 34  content_authors             2438 non-null   str
 35  ref_page                    1044 non-null   str
 36  ref_page_data               1044 non-null   str
 37  category_paths              2436 non-null   str
 38  ind_whatsnew                2438 non-null   int64
 39  ind_outstanding             2438 non-null   int64
 40  scope                       2438 non-null   str
 41  votesignal                  2438 non-null   int64
 42  relatedtechalertcount       1 non-null      float64
 43  status_label                0 non-null      float64
 44  sophia_restricted           2438 non-null   int64
 45  content_subtype_id          2438 non-null   int64
 46  access_groups               2438 non-null   str
 47  deny_groups                 2438 non-null   str
 48  page_views                  2438 non-null   int64
 49  content_type_boost          2438 non-null   int64
 50  typeid                      2438 non-null   int64
 51  template_field              3 non-null      str
 52  relatedto                   159 non-null    float64
 53  lastmodifieddatevalid_day   844 non-null    float64
 54  lastdatevalid_month         844 non-null    str
 55  lastmodifieddatevalid_year  844 non-null    float64
 56  helpdeskname                2438 non-null   str
 57  segmentname                 2438 non-null   str
 58  parent_helpdesk_id          0 non-null      float64
 59  category_name               159 non-null    str
 60  last_modified_date          2438 non-null   str
 61  submitted_date              2438 non-null   str
 62  object_content              2422 non-null   str
 63  object_refpage_data         13 non-null     str
 64  url                         2438 non-null   str
dtypes: float64(7), int64(20), str(38)
memory usage: 1.2 MB
None

In [6]:
print("\nMetadata DataFrame 4:")
print(metadata_df_4.info())

Metadata DataFrame 4:
<class 'pandas.DataFrame'>
RangeIndex: 3755 entries, 0 to 3754
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   version                     3755 non-null   int64
 1   event                       3755 non-null   str
 2   contentid                   3755 non-null   int64
 3   segmentid                   3755 non-null   int64
 4   helpdeskid                  3755 non-null   int64
 5   act_helpdeskid              3755 non-null   int64
 6   status                      3755 non-null   int64
 7   action_by                   0 non-null      float64
 8   assigned_individual         3755 non-null   str
 9   title                       3755 non-null   str
 10  object_summary              3755 non-null   str
 11  submitted_for_area          3278 non-null   str
 12  submitted_for_name          3755 non-null   str
 13  submitted_for_country       3753 non-null   str
 14  submitted_for_geomarket     3278 non-null   str
 15  submitted_for_location      3227 non-null   str
 16  submitted_for_ldap          3755 non-null   str
 17  submitted_year              3755 non-null   int64
 18  submitted_month             3755 non-null   str
 19  submitted_day               3755 non-null   int64
 20  lastmodified_year           3755 non-null   int64
 21  lastmodified_month          3755 non-null   str
 22  lastmodified_day            3755 non-null   int64
 23  ind_publicuser              3755 non-null   int64
 24  num_file_attachments        3755 non-null   int64
 25  keywords                    3755 non-null   str
 26  business_line               3755 non-null   str
 27  content_type                3755 non-null   str
 28  content_subtype             1427 non-null   str
 29  primary_mnemonic            1572 non-null   str
 30  secondary_mnemonic          7 non-null      str
 31  media_type_id               0 non-null      float64
 32  primary_class               3753 non-null   str
 33  quest_ids                   783 non-null    str
 34  content_authors             3755 non-null   str
 35  ref_page                    1204 non-null   str
 36  ref_page_data               1204 non-null   str
 37  category_paths              3755 non-null   str
 38  ind_whatsnew                3755 non-null   int64
 39  ind_outstanding             3755 non-null   int64
 40  scope                       3606 non-null   str
 41  votesignal                  3755 non-null   int64
 42  relatedtechalertcount       2753 non-null   float64
 43  status_label                0 non-null      float64
 44  sophia_restricted           3755 non-null   int64
 45  content_subtype_id          3755 non-null   int64
 46  access_groups               3755 non-null   str
 47  deny_groups                 3755 non-null   str
 48  page_views                  3755 non-null   int64
 49  content_type_boost          3755 non-null   int64
 50  typeid                      3755 non-null   int64
 51  template_field              5 non-null      str
 52  relatedto                   1166 non-null   float64
 53  lastmodifieddatevalid_day   3755 non-null   int64
 54  lastdatevalid_month         3755 non-null   str
 55  lastmodifieddatevalid_year  3755 non-null   int64
 56  helpdeskname                3755 non-null   str
 57  segmentname                 3755 non-null   str
 58  parent_helpdesk_id          0 non-null      float64
 59  category_name               1166 non-null   str
 60  last_modified_date          3755 non-null   str
 61  submitted_date              3755 non-null   str
 62  object_content              3716 non-null   str
 63  object_refpage_data         38 non-null     str
 64  url                         3755 non-null   str
dtypes: float64(6), int64(22), str(37)
memory usage: 1.9 MB
None

In [7]:
metadata_df_4['content_type'].value_counts()

content_type
Case History and Lessons Learned    1368
Best Practice                        770
Documentation                        486
Solution                             477
Announcement                         250
Field Change Order (FCO)             104
Technical Alert                       85
Report                                83
Link                                  68
Reference Page                        38
Training                              26
Name: count, dtype: int64

In [8]:
metadata_df_1['contenttype'].value_counts()

contenttype
Ticket                              4620
Documentation                        376
Best Practice                        322
Solution                             292
Case History and Lessons Learned     278
Training                              58
Announcement                          34
Link                                  20
Reference Page                        14
Report                                12
Technical Alert                        4
Name: count, dtype: int64

In [9]:
metadata_df_1 = metadata_df_1[metadata_df_1['contenttype'] == 'Documentation']

In [10]:
# Keep only the rows that have 'content_type' as 'document'

metadata_df_2 = metadata_df_2[metadata_df_2['content_type'] == 'Documentation']
metadata_df_3 = metadata_df_3[metadata_df_3['content_type'] == 'Documentation']
metadata_df_4 = metadata_df_4[metadata_df_4['content_type'] == 'Documentation']

In [11]:
metadata_df_2.head()

,version,event,contentid,segmentid,helpdeskid,act_helpdeskid,status,action_by,assigned_individual,title,...,lastmodifieddatevalid_year,helpdeskname,segmentname,parent_helpdesk_id,category_name,last_modified_date,submitted_date,object_content,object_refpage_data,url
0,45744,UPDATE,7881302,38980,33321,33321,20,NaN,SSULAIMAN4,ENET FIREWALL STANDARD - SLB-IT-S162,...,2022.0,OFS-IT KNOWLEDGE BASE,IT - Information Technology - TCC,NaN,Obsolete/No Longer Used - Information Technolo...,1/22/2024 0:00,26-Aug-22,This document describes standard design and co...,NaN,https://intouchsupport.com/index.cfm?event=con...
1,47062,UPDATE,7471230,38980,33321,33321,12,NaN,VNAIR13,Software Asset Management Process - SLB-IT-P011,...,2021.0,OFS-IT KNOWLEDGE BASE,IT - Information Technology - TCC,NaN,NaN,1/2/2024 0:00,23-Jan-20,"<span lang=""EN-GB"" style=""margin: 0px; font-si...",NaN,https://intouchsupport.com/index.cfm?event=con...
2,47062,UPDATE,7471230,38980,33321,33321,12,NaN,VNAIR13,Software Asset Management Process - SLB-IT-P011,...,2021.0,OFS-IT KNOWLEDGE BASE,IT - Information Technology - TCC,NaN,NaN,1/2/2024 0:00,23-Jan-20,"<span lang=""EN-GB"" style=""margin: 0px; font-si...",NaN,https://intouchsupport.com/index.cfm?event=con...
3,47062,UPDATE,7471230,38980,33321,33321,12,NaN,VNAIR13,Software Asset Management Process - SLB-IT-P011,...,2021.0,OFS-IT KNOWLEDGE BASE,IT - Information Technology - TCC,NaN,NaN,1/2/2024 0:00,23-Jan-20,"<span lang=""EN-GB"" style=""margin: 0px; font-si...",NaN,https://intouchsupport.com/index.cfm?event=con...
5,47062,UPDATE,6890558,38980,33321,33321,12,NaN,SSULAIMAN4,Cyber Security Corporate Badge Standard - SLB-...,...,2023.0,OFS-IT KNOWLEDGE BASE,IT - Information Technology - TCC,NaN,NaN,12/5/2023 0:00,19-Aug-16,Corporate Badge Standard - SLB-IT-S047<br />Se...,NaN,https://intouchsupport.com/index.cfm?event=con...

In [12]:
main_metadata_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   content_id     182 non-null    int64
 1   content_title  182 non-null    str
 2   attachment_id  182 non-null    int64
 3   file_name      182 non-null    str
 4   domain         182 non-null    str
dtypes: int64(2), str(3)
memory usage: 7.2 KB

In [13]:
main_metadata_df.head()

,content_id,content_title,attachment_id,file_name,domain
0,4532556,Up to date offline documentation system using ...,22938349,KPOD implementation in QTG_4532556_01.pdf,IT
1,5877587,kPod - How to Configure a Role Account for kPod,28706120,Role Accounts_5877587_02.pdf,IT
2,6159418,InTouch Release 8.5 Notes,29491782,Release Notes 7_8_6159418_01.pdf,IT
3,6159418,InTouch Release 8.5 Notes,29491783,Release Notes 7_7 ITE_6159418_01.pdf,IT
4,6159418,InTouch Release 8.5 Notes,29491781,Release Notes 8_0_6159418_01.pdf,IT

In [14]:
metadata_columns = [
    'submitted_for_country',
    'helpdeskname',
    'segmentname',
    'content_type',
    'content_subtype',
]

rename_map = {
    'submittedforcountry': 'submitted_for_country',
    'contenttype': 'content_type',
    'contentsubtype': 'content_subtype',
}


source_dataframes = [metadata_df_1, metadata_df_2, metadata_df_3, metadata_df_4]

normalized_sources = []

for df in source_dataframes:
    tmp = df.rename(columns=rename_map).copy()
    tmp = tmp[tmp['content_type'].eq('Documentation')]
    tmp = tmp[['contentid', *metadata_columns]]
    normalized_sources.append(tmp)

all_metadata_df = (
    pd.concat(normalized_sources, ignore_index=True)
      .drop_duplicates(subset=['contentid'])
)

all_metadata_df.head()

,contentid,submitted_for_country,helpdeskname,segmentname,content_type,content_subtype
0,3333451,FR,SRFE-WL-WLG-DOC-TBT,Reservoir Performance Evaluation,Documentation,Operations Manual
2,3866291,ENG,SRPC-FCS-HCS-CORING-WL,Reservoir Performance Evaluation,Documentation,Operations Manual
4,4017898,OHQ,SRFE-WL (OBSOLETE),Reservoir Performance Intervention,Documentation,Procedure
6,4261968,INM,SRFE-WL (OBSOLETE),Reservoir Performance Intervention,Documentation,Paper
8,4287991,RSS,DSS-A&I-INTOUCH,Digital Subsurface Solutions,Documentation,Procedure

In [16]:
# Delete rows that have a null value in the 'content_type' column
all_metadata_df = all_metadata_df.dropna(subset=['content_type'])

In [ ]:
# Add the filename to each element in the all_metadata_df DataFrame by merging it with the main_metadata_df DataFrame on the 'contentid' column and the 'content_id' column, respectively. After the merge, drop the 'content_id' column from the resulting DataFrame.
all_metadata_df = all_metadata_df.merge(
    main_metadata_df[['content_id', 'file_name']],
    left_on='contentid',
    right_on='content_id',
    how='left'
).drop(columns='content_id', errors='ignore')

In [19]:
# Fill the null values in the 'file_name' column with 'file_not_available_yet'
all_metadata_df['file_name'] = all_metadata_df['file_name'].fillna('file_not_available_yet')

In [20]:
# Add the path to each element.

all_metadata_df["path"] = (
    "parsed_documents/" +
    all_metadata_df["file_name"].str.replace(r"\.pdf$", ".txt", regex=True)
)

In [22]:
all_metadata_df.head()

,contentid,submitted_for_country,helpdeskname,segmentname,content_type,content_subtype,file_name,path
0,3333451,FR,SRFE-WL-WLG-DOC-TBT,Reservoir Performance Evaluation,Documentation,Operations Manual,file_not_available_yet,parsed_documents/file_not_available_yet
1,3866291,ENG,SRPC-FCS-HCS-CORING-WL,Reservoir Performance Evaluation,Documentation,Operations Manual,file_not_available_yet,parsed_documents/file_not_available_yet
2,4017898,OHQ,SRFE-WL (OBSOLETE),Reservoir Performance Intervention,Documentation,Procedure,file_not_available_yet,parsed_documents/file_not_available_yet
3,4261968,INM,SRFE-WL (OBSOLETE),Reservoir Performance Intervention,Documentation,Paper,file_not_available_yet,parsed_documents/file_not_available_yet
4,4287991,RSS,DSS-A&I-INTOUCH,Digital Subsurface Solutions,Documentation,Procedure,file_not_available_yet,parsed_documents/file_not_available_yet

In [24]:
# Export the dataframe to JSON format, each row is an element of the JSON.
all_metadata_df.to_json("metadata_map.json", orient="records", indent=4)

In [47]:
# Explore the different values each column can take.

In [48]:
main_metadata_df['content_subtype'].value_counts()

content_subtype
Standard              73
Guideline             41
Procedure              7
Brochures & Flyers     1
Name: count, dtype: int64

In [49]:
main_metadata_df['content_type'].value_counts()

content_type
Documentation    122
Name: count, dtype: int64

In [50]:
main_metadata_df['domain'].value_counts()

domain
IT    122
Name: count, dtype: int64

In [51]:
main_metadata_df['helpdeskname'].value_counts()

helpdeskname
OFS-IT KNOWLEDGE BASE    121
IWC - GLOBAL               1
Name: count, dtype: int64

In [52]:
main_metadata_df['segmentname'].value_counts()

segmentname
IT - Information Technology - TCC    121
Integrated Well Construction           1
Name: count, dtype: int64

In [53]:
main_metadata_df['submitted_for_country'].value_counts()

submitted_for_country
US     51
GB     36
AE      7
IN      5
NG      5
MY      4
CO      3
CA      3
ID      2
AR      1
FR      1
IE      1
OHQ     1
VN      1
NO      1
Name: count, dtype: int64